// src/components/Navbar.tsx
'use client';
import React from 'react'; 
import { Menubar } from 'primereact/menubar';
import { MenuItem } from 'primereact/menuitem';
import { Button } from 'primereact/button';
import { useRouter } from 'next/navigation'
export default function BasicDemo() {
    const router = useRouter();
    const items: MenuItem[] = [
        {
            label: 'Home',
            icon: 'pi pi-home',
            url:'/page'
        },
        {
            label: 'About',
            icon: 'pi pi-info-circle',
            url:'/about'
        },
        {
            label: 'Projects',
            icon: 'pi pi-star',
            url:'/projects'
        },
        {
            label: 'Skills',
            icon: 'pi pi-book',
            url:'/skills'
        },
        {
            label: 'Contact',
            icon: 'pi pi-linkedin',
            url:'https://www.linkedin.com/in/maicon-alves-03700419b/'
        },
    ];

    const end = (
        <div className="flex align-items-center gap-2">
            <Button label="Download CV" icon="pi pi-download" onClick={donwloadCV} />
        </div>
    );

    function donwloadCV(){
        window.location.href = 'https://github.com'
    }
    
    return (
        <div>
            <Menubar model={items} end={end}/>
        </div>
    )
}

// components/Navbar.vue

<template>
    <div class="card">
        <Menubar :model="items" >
            <template #end>
                <div>
                    <InputText placeholder="Buscar"/>
                </div>
            </template>
        </Menubar>
    </div>
</template>

<script lang="ts">
    export default {
        data() {
            return {
                items: [
                    {
                        label: 'Home',
                    },
                    {
                        label: 'About',
                    },
                    {
                        label: 'Projects',
                        command: () => {
                            window.open('https://github.com/maicond02', '_blank');
                        }
                    },
                    {
                        label: 'Contact',
                        command: () => {
                            window.open('https://www.linkedin.com/in/maicon-alves-03700419b/', '_blank');
                        }
                    }
                ]
            };
        }
    };
</script>

<style scoped>
    :deep(.p-menubar){
        background-color:transparent;
        border:none ;
    }
</style>
